### PR TITLE
Added logging configuration and tested

### PR DESCRIPTION
**Pull request by Chima1707**
Ability to configure logging in the config phase via a provider

### CODE REVIEW

**Comment by Chima1707** [comment]
@tlvince, do you have an idea on how i can increase the semantic version of the module and publish to the npm account?

**Comment by tlvince** [comment]
Since this repo is semantic-release enabled, all you need to do is format the commit message following the [AngularJS conventional changelog conventions](https://github.com/ajoslin/conventional-changelog/blob/master/conventions/angular.md). This would be a `feat` type.

**Comment by tlvince** [comment]
NB, you don't need to rebuild dist (081914a79d53194e183e98365ba9c9cec8913fd4) in this project; semantic-release will do this for you (via [publish-dist](https://www.npmjs.com/package/publish-dist)).

**Comment by tlvince** [comment]
Actually, this may not be necessary; since its using `$log.debug`, consumers of this module can disable logging themselves via [`$logProvider.debugEnabled(false)`](https://code.angularjs.org/1.4.8/docs/api/ng/provider/$logProvider). Sorry, I forgot about this one.

**Comment by Chima1707** [comment]
Then i guess we should close this issue

**Comment by tlvince** [comment]
Could you check that this is the case (via vdd dash)?

**Comment by Chima1707** [comment]
Works, i would add it to the angular production options am working on

**Comment by tlvince** [comment]
Sounds good to me :+1:. Thanks for looking and sorry for the "wasted" effort.

**Pull request closed without merging**
